services:
  node:
    container_name: "backend"
    build: .
    environment:
      - NODE_ENV=prod
    volumes:
      - ./:/home/node/app
    depends_on:
      - mysql
    ports:
      - "3333:3333"
    networks:
      - default
    command: "yarn start"
  mysql:
    container_name: "mysql"
    image: "mysql:8"
    ports:
      - "3306:3306"
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_DATABASE=db
    networks:
      - default
networks:
  default:
volumes:
  db_persdata : {}
