services:
  db:
    container_name: "smartroad-postgres"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smartroad
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - default-smartroad
  node:
    container_name: "smartroad-backend"
    build: .
    environment:
      - NODE_ENV=prod
    volumes:
      - ./:/home/node/app
    depends_on:
      - db
    ports:
      - "3333:3333"
    networks:
      - default-smartroad
    command: "yarn start"
    links:
      - db
networks:
  default-smartroad:
volumes:
  db:
    driver: local
